### ISSUE TITLE
v1.3.7是否没有release

### ISSUE THREAD

**Issue by JoonasKahnwald** [GCS-ZHN/AutoCard#1]
hello，release里面找不到v1.3.7版本，如何下载最新的版本呢

**Comment by GCS-ZHN** [comment]
先去国内同步版仓库下载，https://gitee.com/GCSZHN/AutoCard
应该是我网络原因没上传成功



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ 原始邮件 ------------------
发件人: JoonasKahnwald ***@***.***&gt;
发送时间: 2021年11月11日 11:05
收件人: GCS-ZHN/AutoCard ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [GCS-ZHN/AutoCard] v1.3.7是否没有release (Issue #1)





 
hello，release里面找不到v1.3.7版本，如何下载最新的版本呢
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GCS-ZHN** [comment]
您好，由于网络原因，之前上传失败，已经重新上传

**Comment by JoonasKahnwald** [comment]
多谢~
